// Capy Springs - service worker (generated by tools/pack.js, version 1.6.0): network first, cache fallback, so an installed copy keeps working with no server.
const CACHE = 'capy-springs-1.6.0';
const PRECACHE = ["./","index.html","manifest.webmanifest","icons/icon-192.png","icons/icon-512.png","icons/maskable-512.png","icons/apple-180.png","src/00_config.js","src/01_palette.js","src/02_data_map.js","src/02_data_stations.js","src/02_data_lanterns.js","src/02_data_guests.js","src/03_pack_s2.js","src/04_seasons.js","src/10_util.js","src/11_bus.js","src/12_loop.js","src/13_canvas.js","src/14_camera.js","src/15_input.js","src/16_audio.js","src/17_save.js","src/20_art_shapes.js","src/21_art_chars.js","src/22_art_world.js","src/23_art_fx.js","src/24_fx.js","src/25_art_s2.js","src/30_state.js","src/31_player.js","src/32_trail.js","src/33_guests.js","src/34_cablecar.js","src/35_baths.js","src/36_heat.js","src/37_grove.js","src/38_stall.js","src/39_coins.js","src/40_lanterns.js","src/41_upgrades.js","src/42_helpers.js","src/43_events.js","src/44_hints.js","src/45_render.js","src/46_kaa.js","src/47_ridge.js","src/50_hud.js","src/51_sheet.js","src/52_cards.js","src/53_title.js","src/54_dev.js","src/90_main.js"];
// install never fails on one slow file (a tunnel or a phone network can drop a request): each file is cached on its own, and the
// fetch handler fills in anything missing during normal play
self.addEventListener('install', e => { self.skipWaiting(); e.waitUntil(caches.open(CACHE).then(c => Promise.all(PRECACHE.map(u => fetch(u, { cache: 'no-cache' }).then(r => { if (r && r.ok) return c.put(u, r); }).catch(() => {}))))); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
// network first; a failed or non-OK answer (server off, an expired share link, a host's error page) falls back to the cached copy
const fromCache = req => caches.match(req, { ignoreSearch: true }).then(r => r || (req.mode === 'navigate' ? caches.match('index.html') : undefined));
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || !e.request.url.startsWith(self.location.origin)) return;
  // the page itself is always revalidated with the host (hosts like GitHub Pages otherwise keep it for 10 minutes); its script URLs carry
  // the version, so a new page pulls new scripts and the rest can use the normal HTTP cache
  const init = e.request.mode === 'navigate' ? { cache: 'no-cache' } : undefined;
  e.respondWith(fetch(e.request, init).then(res => {
    if (res && res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); return res; }
    return fromCache(e.request).then(r => r || res);
  }).catch(() => fromCache(e.request).then(r => r || Response.error())));
});
